### ISSUE TITLE
Don't check OP status with rank sync hasPermission

### ISSUE THREAD

**Issue by david50407** [Scarsz/DiscordSRV#203]
Request for PermissionEx (and any other permission manager plugins) support directly.

When using Minecraft permission to Discord role syncing, if the player is Op, the bukkit `hasPermission` always returns `true`, and this causes any Op player get all Discord role which as listed in the sync id list.

By calling PermissionEx api directly can prevent this problem and this is useful to building teaming in Discord, our server use the `permission -> role` syncing for building a MMORPG-like chat system.
With this issue, the Op player will be assigned into all teams, but we want that each player can only join a team even if the player is Op/Admin.

**Comment by MaxiMiniJaniJos** [comment]
Use permission negation.
Or don't have ops and just give them permissions.

**Comment by david50407** [comment]
The `hasPermission` will first check if the player has op and return true, so negation is not worked.

And if the moderator doesn't has op flag, he/she cannot use some vanilla functions like editing command blocks.

**Comment by MaxiMiniJaniJos** [comment]
First off I'm pretty sure that negating works even for ops, from what I've learnt while developing but ofcourse I might be wrong.
The I come to the point that why would a moderator need to edit a command block? I think that's a bit overpowered and no moderator should have to do it in the first place but ofcourse every server has their own ideas etc.. So that's not up to me to say.
Then there are permission nodes for vanilla commands and other vanilla features.
Just look them up and even if you can't find it there is probably a plugin for it out there. Though you probably don't have to use a plugin because there are nodes for them.

**Comment by Scarsz** [comment]
Moderators shouldn't have op lol

I'll make it so op status isn't checked for role sync

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/2b18d7974d6defbc1081a95a365aae5f6150db0c

**Comment by david50407** [comment]
wow nice work
