### ISSUE TITLE
Whitelist based upon discord role

### ISSUE THREAD

**Issue by jgaski3** [Scarsz/DiscordSRV#278]
Since discordSRV can handle bans i think another option that would help our discord out is to update the whiltelist based upon a users role. We set aside a specific role to grant users access to the channel for minecraft but it would be great if it could also modify the whiltelist based upon them getting the role.

**Comment by Androkai** [comment]
If you mean the Minecraft server's whitelist with "whitelist":
To whitelist a player we first need to now which Minecraft account goes with which Discord account. That because why accounts needs to be linked first. To link the player needs to be on the server first. --> We can't whitelist a who is not already on the server.
