### ISSUE TITLE
NPE from invalid JSON

### ISSUE THREAD

**Issue by Scarsz** [Scarsz/DiscordSRV#33]
originally add snapshot ids to builds

**Comment by Scarsz** [comment]
finished @Androkai

**Comment by Androkai** [comment]
Great feature, good job! @Scarsz 

Some suggestions:

1.) Replace message of the day (MOTD) in first line of debug-output with servername from server.properties and maybe add MOTD in the next line.

2.) For a test I malformed my channels.json and create a NullPointerException. This can't be figured out with the resulting debug-message because the stacktrace is shortened and there is no additional information in channels.json-part like you can see [here](http://hastebin.com/yukeginote). Some idea from my side are adding parsing of channels.json and inform in the logs about (maybe also with the problematic position in code) + adding a 1:1 copy of channels.json to the debug-message to make us able helping incompetent admins. It would be also nice if the full stacktrace (every following line stating with a tab) is shown.

3.) The debug-message contains some information about the server. Maybe not everybody wants to have this public. I suggest to document that this happens then using /discord debug. Another idea is using a paste-system like [ZeroBin](http://sebsauvage.net/wiki/doku.php?id=php:zerobin). Sadly this is less pretty than hastebin.

**Comment by Scarsz** [comment]
1 was already being done, 2 deserves a NPE exception catch near
https://github.com/Scarsz/DiscordSRV/blob/develop/src/main/java/com/scarsz/discordsrv/DiscordSRV.java#L201,
3
I don't care about

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/3710aecb5baaeb213ce4aad4c12f0dfc430d5937

**Comment by Androkai** [comment]
Works now also if it's a bit malformed but if the channel-IDs are ok and another part of the json is malformed (e.g. a comma after the last entry) it still throws a [NullPointerException](http://hastebin.com/azomamobut.avrasm) at startup.

Btw: @1.) it's still the MOTD for me: http://hastebin.com/owiwihapap
The correct server-name is "BigCraftDEV" for this server.

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/90b5aec423d7f28069c5b73d8cc5a0681b190de5 & https://github.com/Scarsz/DiscordSRV/commit/bf4a3d78d487e4f8ce575bce3bf21770d735248d

**Comment by Androkai** [comment]
1.) looks good now: http://hastebin.com/iciricowez :)

**Comment by Androkai** [comment]
Still the NullPointerException

**Comment by Scarsz** [comment]
todo: add a JSON verification before attempting to load it

**Comment by Scarsz** [comment]
this is actually technically already done, not sure what can really be done about this
