### ISSUE TITLE
McMMO support

### ISSUE THREAD

**Issue by Scarsz** [Scarsz/DiscordSRV#84]
@Androkai please collect some info about what needs to be done for this

**Comment by Androkai** [comment]
mcMMO is a bit special because it's often run next to a dedicated chat plugin like for example VentureChat. mcMMO provides in addition to the normal chat channel an **admin channel** and **party chats**. Admin channel is worth to implement as a choose able channel to link to Discord, party chats should be only removed / prevented from being send to Discord until we have to much time to implement a solution which automatically creates a new Discord-channel for every new party chat and gives the linked players access to read/write to. #suggestion

**Code for pom.xml:**
```
        <!-- File is already available within one of our other dependencies but I recommend to add this to be on the save side -->
        <repository>
            <id>mcMMO</id>
            <url>http://maven.elmakers.com/repository/</url>
        </repository>
        ...
        <!-- The doubled "mcMMO" is no mistake :/ -->
        <!-- mcMMO -->
        <dependency>
            <groupId>com.gmail.nossr50.mcMMO</groupId>
            <artifactId>mcMMO</artifactId>
            <version>1.5.00</version>
            <scope>provided</scope>
        </dependency>
```
An API is given so the only thing to think about is how to implement this to be able to run next to one of the other channel supporting plugins.

![A picture with the classes](https://androkai.net/bilder/mcMMO-1.5.00_classes.png)

**Comment by Scarsz** [comment]
All we need is `ChatAPI.isPartyChat(#Player)`, this issue is pertaining to party chat in particular showing up when it obviously shouldn't be

**Comment by Scarsz** [comment]
All we'd really need is `ChatAPI.isUsingPartyChat(player)` cause this is
more about party chat specifically appearing in discord when it obviously
shouldn't

**Comment by Androkai** [comment]
Fixed with https://github.com/Scarsz/DiscordSRV/commit/1d2f8ee51a3b4d815b0f8f049879176bd62fb48c by preventing mcMMO's admin and party chat from being send to Discord.

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/8d9f8de310b4817c0a7c8600ff83ac115404ae04
